export enum TypeOperationStockTracker {
  REQUISICION = 'REQUISICION',
  VENTA = 'VENTA',
  AJUSTE_STOCK = 'AJUSTE_STOCK',
  ELIMINACION_STOCK = 'ELIMINACION_STOCK',
  ELIMINACION_VENTA = 'ELIMINACION_VENTA',
  TRANSFERENCIA_PRODUCTO = 'TRANSFERENCIA_PRODUCTO',
  ENTREGA_STOCK = 'ENTREGA_STOCK',
}
